<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Db;
class StudentProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
$students=[
    [
        'user_id'=>'19',
        'department_id'=>'1',
        'semester_id'=>'1',
        'batch_id'=>'1',
        'firstname'=>'Joy',
        'lastname'=>'dhar',
        'roll_number'=>'17010132',
        'registration_number'=>'682',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'20',
        'department_id'=>'1',
        'semester_id'=>'2',
        'batch_id'=>'2',
        'firstname'=>'Marjan',
        'lastname'=>'Mia',
        'roll_number'=>'17010110',
        'registration_number'=>'610',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],

    [
        'user_id'=>'21',
        'department_id'=>'1',
        'semester_id'=>'1',
        'batch_id'=>'1',
        'firstname'=>'Student1',
        'lastname'=>'lastname',
        'roll_number'=>'17010132',
        'registration_number'=>'682',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'22',
        'department_id'=>'1',
        'semester_id'=>'2',
        'batch_id'=>'2',
        'firstname'=>'Student2',
        'lastname'=>'last name',
        'roll_number'=>'17010110',
        'registration_number'=>'610',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],

    [
        'user_id'=>'23',
        'department_id'=>'1',
        'semester_id'=>'3',
        'batch_id'=>'1',
        'firstname'=>'student_semester3',
        'lastname'=>'dhar',
        'roll_number'=>'17010132',
        'registration_number'=>'682',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'24',
        'department_id'=>'1',
        'semester_id'=>'4',
        'batch_id'=>'2',
        'firstname'=>'Student',
        'lastname'=>'semester_4',
        'roll_number'=>'17010110',
        'registration_number'=>'610',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],

    [
        'user_id'=>'25',
        'department_id'=>'1',
        'semester_id'=>'5',
        'batch_id'=>'1',
        'firstname'=>'student_semester5',
        'lastname'=>'lastname',
        'roll_number'=>'17010132',
        'registration_number'=>'682',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'26',
        'department_id'=>'1',
        'semester_id'=>'6',
        'batch_id'=>'2',
        'firstname'=>'student',
        'lastname'=>'semester 6',
        'roll_number'=>'17010110',
        'registration_number'=>'610',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'27',
        'department_id'=>'1',
        'semester_id'=>'7',
        'batch_id'=>'1',
        'firstname'=>'student7',
        'lastname'=>'semester 7',
        'roll_number'=>'17010132',
        'registration_number'=>'682',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
    [
        'user_id'=>'28',
        'department_id'=>'1',
        'semester_id'=>'8',
        'batch_id'=>'2',
        'firstname'=>'student 8',
        'lastname'=>'semester 8',
        'roll_number'=>'17010110',
        'registration_number'=>'610',
        'phone'=>'01774861411',
        'address'=>'anwara',
        'blood_group'=>'A+',
        'hsc_gpa'=>'4.17',
        'ssc_gpa'=>'5.00',
        'jsc_gpa'=>'4.86',
        'psc_gpa'=>'5.00',
    ],
];




      DB::table('students')->insert($students);

    }
}
